add_organization_tab = "//span[contains(normalize-space(),'Add Organization')]"
email_field = "//input[@placeholder='Enter your email ID here']"
tripjack_navigation_button = "(//div[@class='d-flex MuiBox-root css-0'])[1]"
super_admin_profile = "//div[text()='Super Admin']"
my_organization_text = "//div[@class='MuiTypography-root MuiTypography-h4 cursorPointer css-mrlhye']"
login_next_button = "//span[@class='MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-fullWidth MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-fullWidth css-1fi99zc']"
disabled_login_next_button = "//span[@aria-disabled='true']"
corporate_traveller_home_navigation_text = "//div[text()='Your Corporate Travel']"
hotels_option = '//button[contains(@class,"MuiButtonBase-root")]//div[normalize-space()="Hotels"]'
otp_field = "//input[@aria-label='Please enter OTP character 1']"
verify_otp_button = "//span[contains(normalize-space(),'Verify')]"
unregistered_email_error_message = "//div[contains(text(),'User email not found in the database')]"
disabled_login_verify_button = "//span[@aria-disabled='true' and text()='Verify']"
corporate_admin_my_organization_text = "//span[@aria-label='My Organization']"
my_organization_tab="//span[@class='icon-buildings']"
